### ISSUE TITLE
Use zpoline to hook system call

### ISSUE THREAD

**Issue by jserv** [sholtrop/ldpfuse#4]
Programs that use inline system calls (such as using the `syscall` directly) or those that statically link to glibc cannot utilize LDP_FUSE. This is because `LD_PRELOAD` is not sufficient, as it can not fully hook into all system calls.

The [zpoline](https://github.com/yasukata/zpoline) falls under the category of binary rewriting. However, it's important to note that it doesn't overwrite your program's binary files. Instead, [zpoline](https://github.com/yasukata/zpoline) modifies the binary code in memory just before the program's main function begins. This means your original program files remain unchanged. [zpoline](https://github.com/yasukata/zpoline) offers reasonable speed, and integrating it with LDP_FUSE could be beneficial. Please consider this integration possibility.

**Comment by sholtrop** [comment]
Very cool! Will look into it
